package capagrafica;

import capalogica.Cine;
import capalogica.Pelicula;
import java.awt.Graphics;
import java.awt.Image;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Kevin Hidalgo
 */
public class VentanaAdministracion extends javax.swing.JFrame {
       FondoPanel fondo=new FondoPanel();
       private final Cine miCine;
       private static int consecutivoSalas=0; // para iniciar numero sala en 0
       private int numeroSala;
    /**
     * Creates new form VentanaAdministracion
     */
    public VentanaAdministracion(Cine miCine) {
        this.setContentPane(fondo);     
        this.miCine = miCine;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnMostrarSala = new javax.swing.JButton();
        btnReporteIngreso = new javax.swing.JButton();
        btnReporteAsientos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(991, 720));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Administrar Cartelera");

        btnCrear.setBackground(new java.awt.Color(153, 153, 0));
        btnCrear.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Crear Cartelera");
        btnCrear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnMostrarSala.setBackground(new java.awt.Color(153, 153, 0));
        btnMostrarSala.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnMostrarSala.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarSala.setText("Mostrar Salas");
        btnMostrarSala.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnMostrarSala.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarSalaActionPerformed(evt);
            }
        });

        btnReporteIngreso.setBackground(new java.awt.Color(153, 153, 0));
        btnReporteIngreso.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnReporteIngreso.setForeground(new java.awt.Color(255, 255, 255));
        btnReporteIngreso.setText("Reporte Ingreso Salas");
        btnReporteIngreso.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnReporteIngreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporteIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteIngresoActionPerformed(evt);
            }
        });

        btnReporteAsientos.setBackground(new java.awt.Color(153, 153, 0));
        btnReporteAsientos.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnReporteAsientos.setForeground(new java.awt.Color(255, 255, 255));
        btnReporteAsientos.setText("Reporte Asientos Comprados Salas");
        btnReporteAsientos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnReporteAsientos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporteAsientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteAsientosActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(153, 153, 0));
        btnSalir.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Regresar Menu Anterior");
        btnSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        txtResultados.setBackground(new java.awt.Color(240, 240, 240));
        txtResultados.setColumns(20);
        txtResultados.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        txtResultados.setRows(5);
        jScrollPane1.setViewportView(txtResultados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMostrarSala, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReporteIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReporteAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(964, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnMostrarSala, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReporteIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnReporteAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String nombre =  JOptionPane.showInputDialog(null, "Digite el nombre de la pelicula: ");
       
       try {  
           String fechaTexto = JOptionPane.showInputDialog(null, "Digite la fecha en que se impartira la pelicula (ejemplo:15/12/2024)");
            // Formato de fecha
           SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
           Date fecha = formatoFecha.parse(fechaTexto); 
           numeroSala = consecutivoSalas++; // aumenta en 1 el numero de sala para la siguiente pelicula
           Pelicula miPelicula = new Pelicula(nombre, numeroSala,fecha);    // String nombre, int numeroSala,date
          String hora = JOptionPane.showInputDialog(null, "Digite la hora (00:00)");
          if(hora.matches("^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]?$")){
            miPelicula.setHora(hora);
          }else{
           JOptionPane.showMessageDialog(null,"La hora tiene un formato incorrecto");
           return;
          } 
        
           if(this.miCine.ingresarPelicula(miPelicula)){
                 JOptionPane.showMessageDialog(null,"Pelicula ingresada satisfactoriamente");
                 miCine.setExistePelicula(true); // para indicar que al menos hay una pelicula en la cartelera
                 txtResultados.setText(miCine.mostrarCartelera());
           }else{
                 JOptionPane.showMessageDialog(null,"Ya existe una pelicula con ese Nombre o solo puedes agregar 3 peliculas");
                  numeroSala = consecutivoSalas--; // disminuye en 1 el numero de sala porque la pelicula no pudo guardarse
           }   
           }catch(ParseException e){
               JOptionPane.showMessageDialog(null, "La fecha tiene un formato incorrecto");
           }
            
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnMostrarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarSalaActionPerformed
        int sala=1;
        try{
        sala =  Integer.parseInt(JOptionPane.showInputDialog(null, "Digite el numero de sala: (1,2,3)"));
          if(sala>=1 && sala<=3){
                txtResultados.setText(miCine.mostrarSala(sala));
            }else{
                JOptionPane.showMessageDialog(null, "Debe ser una sala entre 1 y 3");
            }
        }catch(Exception e){
              JOptionPane.showMessageDialog(null, "Debe digitar numeros");
        }
          
    }//GEN-LAST:event_btnMostrarSalaActionPerformed

    private void btnReporteIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteIngresoActionPerformed
        int sala=1; 
        try{
        sala =  Integer.parseInt(JOptionPane.showInputDialog(null, "Digite el numero de sala: (1,2,3)"));
          if(sala>=1 && sala<=3){
            txtResultados.setText("\nSala N-"+ sala + "\nReporte Ingresos: ₵" + miCine.getPeliculas()[sala-1].getVentas());
            }else{
                JOptionPane.showMessageDialog(null, "Debe ser una sala entre 1 y 3");
            }
        }catch(Exception e){
              JOptionPane.showMessageDialog(null, "Debe digitar numeros o crear la pelicula correspondiente a la sala");
        }
    }//GEN-LAST:event_btnReporteIngresoActionPerformed

    private void btnReporteAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteAsientosActionPerformed
        int sala=1; 
        try{
        sala =  Integer.parseInt(JOptionPane.showInputDialog(null, "Digite el numero de sala: (1,2,3)"));
          if(sala>=1 && sala<=3){
            txtResultados.setText("\nSala N-"+ sala + "\nAsientos Comprados: " + miCine.totalCantidadAsientos(sala));
            }else{
                JOptionPane.showMessageDialog(null, "Debe ser una sala entre 1 y 3");
            }
        }catch(Exception e){
              JOptionPane.showMessageDialog(null, "Debe digitar numeros");
        }
      
    }//GEN-LAST:event_btnReporteAsientosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
      VentanaMenuInicial miVentana = new VentanaMenuInicial(miCine);
      miVentana.setVisible(true);
      miVentana.setResizable(false);
      miVentana.setTitle("GOLDEN Cine Alajuela (MENU PRINCIPAL)");
      miVentana.setLocationRelativeTo(null);
      this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnMostrarSala;
    private javax.swing.JButton btnReporteAsientos;
    private javax.swing.JButton btnReporteIngreso;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtResultados;
    // End of variables declaration//GEN-END:variables
  class FondoPanel extends JPanel
    {
        private Image imagen;
        public void paint(Graphics g)
        {
        imagen = new ImageIcon(getClass().getResource("/imagenes/administrarCartelera.png")).getImage();
        g.drawImage(imagen, 0, 0, getWidth(),getHeight(),this);
        setOpaque(false);
        super.paint(g);
        }
    }
}
